@Address = https://localhost:7000

###

GET {{Address}}/api/images
Accept: application/json

###

GET {{Address}}/api/images/cars/1HGCM82633A000001
Accept: application/json

###

GET {{Address}}/api/images/motorcycles/3HDMC82633M000101
Accept: application/json

###

GET {{Address}}/api/users/status
Accept: application/json

###

GET {{Address}}/api/users
Accept: application/json

###

POST {{Address}}/api/users/login?email=fajni@gmail.com&password=fajni123
Accept: application/json
Content-Type: application/json

###

POST {{Address}}/api/images/add
Accept: application/json
Content-Type: application/json

{
    "src": "https://www.panorica.com/sites/default/files/second-image-gallery/Dacia-Sandero-2022.jpg",
    "carVin": "2DACM82633A000013"
}