@Address = https://localhost:7000

###

GET {{Address}}/api/users
Accept: application/json

###

GET {{Address}}/api/test
Accept: application/json

###

GET {{Address}}/api/protected
Accept: application/json

###

GET {{Address}}/api/users/2
Accept: application/json

###

GET {{Address}}/api/users/logout
Accept: application/json

###

POST {{Address}}/api/users/registration
Accept: application/json
Content-Type: application/json

{
    "Firstname": "John",
    "Lastname": "Doe",
    "Email": "john@gmail.com",
    "Password": "john123",
    "Role": "User"
}

### 

DELETE {{Address}}/api/users/delete/4
Accept: application/json

###

PUT {{Address}}/api/users/update/1
Accept: application/json
Content-Type: application/json

{
    "Firstname": "John",
    "Lastname": "Doe",
    "Email": "john@gmail.com",
    "Password": "john123",
    "Role": "Admin"
}

###

POST {{Address}}/api/users/login?email=paige@gmail.com&password=paige123
Accept: application/json
Content-Type: application/json

{
}

###

POST {{Address}}/api/users/login?email=fajni@gmail.com&password=fajni123
Accept: application/json
Content-Type: application/json

{
}

### 
GET {{Address}}/api/users/status
Accept: application/json